//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrasscutterTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrasscutterTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 28010101: 黄金蟹
        ///28010102: 太阳蟹
        ///28010103: 海蓝蟹
        ///28010104: 将军蟹
        ///28010105: 薄红蟹
        ///28010106: 螃蟹
        ///28020101: 雪狐
        ///28020102: 红狐
        ///28020103: 送礼雪狐
        ///28020104: 送大礼雪狐
        ///28020105: 雪狐
        ///28020106: 红狐
        ///28020201: 松鼠
        ///28030101: 蓝翎鹭
        ///28030102: 菫鹮
        ///28030201: 茶羽鹰
        ///28030202: 棕翎鹰
        ///28030203: 石鸢
        ///28030204: 白练鹰
        ///28050101: 风晶蝶
        ///28050102: 岩晶蝶
        ///28050103: 冰晶蝶
        ///28050104: 雷晶蝶
        ///28050105: 珊瑚蝶
        ///28050301: 吉光虫
        ///28010201: 蓝角蜥
        ///28010202: 红角蜥
        ///28010203: 绿角蜥
        ///28010204: 落日鳅鳅
        ///28010205: 金鳅鳅
        ///28010206: 晴天鳅鳅
        ///28010207: 嗜髓蜥
        ///28010301: 青蛙
        ///28010302: 泥蛙
        ///2801030 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Animal {
            get {
                return ResourceManager.GetString("Animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 51110: 异国之盏
        ///51111: 异国之盏
        ///51112: 异国之盏
        ///51113: 异国之盏
        ///51114: 异国之盏
        ///51120: 归乡之羽
        ///51121: 归乡之羽
        ///51122: 归乡之羽
        ///51123: 归乡之羽
        ///51124: 归乡之羽
        ///51130: 感别之冠
        ///51131: 感别之冠
        ///51132: 感别之冠
        ///51133: 感别之冠
        ///51134: 感别之冠
        ///51140: 故人之心
        ///51141: 故人之心
        ///51142: 故人之心
        ///51143: 故人之心
        ///51144: 故人之心
        ///51150: 逐光之石
        ///51151: 逐光之石
        ///51152: 逐光之石
        ///51153: 逐光之石
        ///51154: 逐光之石
        ///51210: 异国之盏
        ///51211: 异国之盏
        ///51212: 异国之盏
        ///51213: 异国之盏
        ///51214: 异国之盏
        ///51220: 归乡之羽
        ///51221: 归乡之羽
        ///51222: 归乡之羽
        ///51223: 归乡之羽
        ///51224: 归乡之羽
        ///51230: 感别之冠
        ///51231: 感别之冠
        ///51232: 感别之冠
        ///51233: 感别之冠
        ///51234 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Artifact {
            get {
                return ResourceManager.GetString("Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 51: 行者之心
        ///52: 勇士之心
        ///53: 守护之心
        ///54: 奇迹
        ///55: 战狂
        ///56: 武人
        ///57: 教官
        ///58: 赌徒
        ///59: 流放者
        ///60: 冒险家
        ///61: 幸运儿
        ///62: 学士
        ///63: 游医
        ///71: 冰风迷途的勇士
        ///72: 平息鸣雷的尊者
        ///73: 渡过烈火的贤人
        ///74: 被怜爱的少女
        ///75: 角斗士的终幕礼
        ///76: 翠绿之影
        ///77: 流浪大地的乐团
        ///78: 冰之川与雪之砂
        ///79: 如雷的盛怒
        ///80: 炽烈的炎之魔女
        ///81: 昔日宗室之仪
        ///82: 染血的骑士道
        ///83: 祭火之人
        ///84: 祭水之人
        ///85: 祭雷之人
        ///86: 祭风之人
        ///87: 祭冰之人
        ///88: 悠古的磐岩
        ///89: 逆飞的流星
        ///90: 沉沦之心
        ///91: 千岩牢固
        ///92: 苍白之火
        ///93: 追忆之注连
        ///94: 绝缘之旗印
        ///95: 华馆梦醒形骸记
        ///96: 海染砗磲
        ///97: 辰砂往生录
        ///98: 来歆余响
        ///99: 高天的风之主 的本地化字符串。
        /// </summary>
        internal static string ArtifactCat {
            get {
                return ResourceManager.GetString("ArtifactCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10001: 生命值
        ///10002: 生命值百分比
        ///10003: 攻击力
        ///10004: 攻击力百分比
        ///10005: 防御力
        ///10006: 防御力百分比
        ///10007: 元素充能效率
        ///10008: 元素精通
        ///10009: 火元素抗性
        ///10010: 雷元素抗性
        ///10011: 冰元素抗性
        ///10012: 水元素抗性
        ///10013: 风元素抗性
        ///10014: 岩元素抗性
        ///10015: 草元素抗性
        ///12001: 攻击力
        ///13001: 生命值
        ///13002: 生命值百分比
        ///13003: 攻击力
        ///13004: 攻击力百分比
        ///13005: 防御力
        ///13006: 防御力百分比
        ///13007: 暴击率
        ///13008: 暴击伤害
        ///13009: 治疗加成
        ///13010: 元素精通
        ///14001: 生命值
        ///15001: 生命值
        ///15002: 生命值百分比
        ///15003: 攻击力
        ///15004: 攻击力百分比
        ///15005: 防御力
        ///15006: 防御力百分比
        ///15007: 元素精通
        ///15008: 火元素伤害加成
        ///15009: 雷元素伤害加成
        ///15010: 冰元素伤害加成
        ///15011:  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ArtifactMainAttribution {
            get {
                return ResourceManager.GetString("ArtifactMainAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空之杯,死之羽,理之冠,生之花,时之沙 的本地化字符串。
        /// </summary>
        internal static string ArtifactPartLabels {
            get {
                return ResourceManager.GetString("ArtifactPartLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 101021: 生命值+24
        ///101022: 生命值+30
        ///201021: 生命值+50
        ///201022: 生命值+61
        ///201023: 生命值+72
        ///301021: 生命值+100
        ///301022: 生命值+115
        ///301023: 生命值+129
        ///301024: 生命值+143
        ///401021: 生命值+167
        ///401022: 生命值+191
        ///401023: 生命值+215
        ///401024: 生命值+239
        ///501021: 生命值+209
        ///501022: 生命值+239
        ///501023: 生命值+269
        ///501024: 生命值+299
        ///101031: 生命值百分比+1.2%
        ///101032: 生命值百分比+1.5%
        ///201031: 生命值百分比+1.6%
        ///201032: 生命值百分比+2.0%
        ///201033: 生命值百分比+2.3%
        ///301031: 生命值百分比+2.4%
        ///301032: 生命值百分比+2.8%
        ///301033: 生命值百分比+3.2%
        ///301034: 生命值百分比+3.5%
        ///401031: 生命值百分比+3.3%
        ///401032: 生命值百分比+3.7 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ArtifactSubAttribution {
            get {
                return ResourceManager.GetString("ArtifactSubAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除？ 的本地化字符串。
        /// </summary>
        internal static string AskConfirmDeletion {
            get {
                return ResourceManager.GetString("AskConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10000001: 凯特
        ///10000002: 神里绫华
        ///10000003: 琴
        ///10000005: 旅行者
        ///10000006: 丽莎
        ///10000007: 旅行者
        ///10000014: 芭芭拉
        ///10000015: 凯亚
        ///10000016: 迪卢克
        ///10000020: 雷泽
        ///10000021: 安柏
        ///10000022: 温迪
        ///10000023: 香菱
        ///10000024: 北斗
        ///10000025: 行秋
        ///10000026: 魈
        ///10000027: 凝光
        ///10000029: 可莉
        ///10000030: 钟离
        ///10000031: 菲谢尔
        ///10000032: 班尼特
        ///10000033: 达达利亚
        ///10000034: 诺艾尔
        ///10000035: 七七
        ///10000036: 重云
        ///10000037: 甘雨
        ///10000038: 阿贝多
        ///10000039: 迪奥娜
        ///10000041: 莫娜
        ///10000042: 刻晴
        ///10000043: 砂糖
        ///10000044: 辛焱
        ///10000045: 罗莎莉亚
        ///10000046: 胡桃
        ///10000047: 枫原万叶
        ///1000004 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1001:purple
        ///1002:yellow
        ///1003:yellow
        ///1005:yellow
        ///1006:purple
        ///1007:yellow
        ///1014:purple
        ///1015:purple
        ///1016:yellow
        ///1020:purple
        ///1021:purple
        ///1022:yellow
        ///1023:purple
        ///1024:purple
        ///1025:purple
        ///1026:yellow
        ///1027:purple
        ///1029:yellow
        ///1030:yellow
        ///1031:purple
        ///1032:purple
        ///1033:yellow
        ///1034:purple
        ///1035:yellow
        ///1036:purple
        ///1037:yellow
        ///1038:yellow
        ///1039:purple
        ///1041:yellow
        ///1042:yellow
        ///1043:purple
        ///1044:purple
        ///1045:purple
        ///1046:yellow
        ///1047:yellow
        ///1048:purple
        ///1049:yellow
        ///1050:purple
        ///1051:yellow
        ///1052: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AvatarColor {
            get {
                return ResourceManager.GetString("AvatarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] AvatarStats {
            get {
                object obj = ResourceManager.GetObject("AvatarStats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 浏览器打开失败，你可以通过以下链接手动访问： 的本地化字符串。
        /// </summary>
        internal static string BrowserOpenFailedTip {
            get {
                return ResourceManager.GetString("BrowserOpenFailedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查到新版本 的本地化字符串。
        /// </summary>
        internal static string CheckToNewVersion {
            get {
                return ResourceManager.GetString("CheckToNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无,晴天,多云,雨天,雷暴,雪天,雾天 的本地化字符串。
        /// </summary>
        internal static string ClimateType {
            get {
                return ResourceManager.GetString("ClimateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒后可重发 的本地化字符串。
        /// </summary>
        internal static string CodeResendTip {
            get {
                return ResourceManager.GetString("CodeResendTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送中... 的本地化字符串。
        /// </summary>
        internal static string CodeSending {
            get {
                return ResourceManager.GetString("CodeSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令内容不能为空 的本地化字符串。
        /// </summary>
        internal static string CommandContentCannotBeEmpty {
            get {
                return ResourceManager.GetString("CommandContentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到该命令 的本地化字符串。
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令标签不能为空 的本地化字符串。
        /// </summary>
        internal static string CommandTagCannotBeEmpty {
            get {
                return ResourceManager.GetString("CommandTagCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现在你可以远程执行命令了哦！ 的本地化字符串。
        /// </summary>
        internal static string ConnectedTip {
            get {
                return ResourceManager.GetString("ConnectedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无敌
        ////godmode
        ///无限耐力
        ////nostamina
        ///升到60级
        ////give 102 1880200
        ///奶
        ////heal
        ///我全都要！
        ////giveall
        ///我在哪？
        ////position
        ///设置世界等级
        ////setworldlevel 8
        ///设置羁绊等级
        ////setfetterlevel 1
        ///清空背包
        ////clear all
        ///清空武器
        ////clear wp
        ///清空圣物
        ////clear art
        ///清空材料
        ////clear mat
        ///发送广播
        ////broadcast 大家好啊~
        ///清空当前角色命之座(需重登)
        ////resetconst
        ///清空全部角色命之座(需重登)
        ////resetconst all
        ///一万纠缠
        ////give 223 10000
        ///一万相遇
        ////give 224 10000
        ///十万原石
        ////give 201 100000
        ///十万摩拉
        ////give 202 100000
        ///速速集合！
        ////tpall
        ///拔线
        ////restart
        ///私信
        ////say &lt;player&gt; &lt;message&gt;
        ///进来吧你
        ////coop @targetId
        ///自杀
        ////killcharacter
        ///暗杀
        //// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CustomCommands {
            get {
                return ResourceManager.GetString("CustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 007: 初行者推荐祈愿
        ///008: 奔行世间
        ///009: 杯装之诗
        ///010: 黎明巡礼
        ///011: 南风之眷
        ///012: 靖妖傩舞
        ///013: 神铸赋形
        ///015: 闪焰的驻足
        ///016: 初行者推荐祈愿
        ///017: 奔行世间
        ///018: 闪焰的驻足
        ///019: 杯装之诗
        ///020: 神铸赋形
        ///021: 神铸赋形
        ///022: 奔行世间
        ///023: 暂别冬都
        ///024: 陵薮市朝
        ///027: 深秘之息
        ///028: 浮生孰来
        ///031: 烟火之邀
        ///032: 鱼龙灯昼
        ///033: 赤团开时
        ///036: 杯装之诗
        ///037: 暂别冬都
        ///040: 陵薮市朝
        ///041: 浪涌之瞬
        ///045: 叶落风随
        ///048: 白鹭之庭
        ///049: 焰色天河
        ///052: 影寂天下人
        ///053: 浮岳虹珠
        ///061: 鬼门斗宴
        ///065: 出尘入世
        ///071: 华紫樱绯
        ///076: 苍流踏花 的本地化字符串。
        /// </summary>
        internal static string GachaBennerPrefab {
            get {
                return ResourceManager.GetString("GachaBennerPrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon IconGrasscutter {
            get {
                object obj = ResourceManager.GetObject("IconGrasscutter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgHome {
            get {
                object obj = ResourceManager.GetObject("ImgHome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgIconGrasscutter {
            get {
                object obj = ResourceManager.GetObject("ImgIconGrasscutter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgSupport {
            get {
                object obj = ResourceManager.GetObject("ImgSupport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 101: 角色经验
        ///102: 冒险阅历
        ///103: 星尘
        ///104: 星辉
        ///105: 好感经验
        ///106: 原粹树脂
        ///107: 传说钥匙
        ///108: (test)天体推演
        ///109: 熄星能量
        ///110: 熄星精粹
        ///111: 微光精粹
        ///112: 温暖精粹
        ///113: 奇迹精粹
        ///114: 铁钱
        ///115: 平安玉符
        ///116: 节庆热度
        ///117: 奇术符
        ///118: 庆典巡回券
        ///119: 奇趣协力券
        ///120: 纯水真心
        ///121: 信任值
        ///122: 碎果数据
        ///123: 迷踪币
        ///124: 亮闪闪的漂流物
        ///125: 迷你「羽球」
        ///126: 神秘齿轮
        ///127: 鸣雷霰子
        ///128: 鸣雷纯晶
        ///129: 弈棋术经验
        ///130: 灵妙玉符
        ///131: 逐月节节庆热度
        ///132: 残悴之式札
        ///133: 虚损之拓本
        ///134: 朽裂之庚牌
        ///135: 踏雪章
        ///136: 克险章
        ///137: 逢福玉符
        ///138: 完璧玉符
        ///139: 降魔玉符
        ///201: 原石
        ///202: 摩拉
        ///203: 创世结晶
        ///204: 洞天宝钱
        ///210: 原粹精珀（废弃）
        ///211: 原粹树脂（废弃）
        ///221: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 21010101: 丘丘人
        ///21020101: 木盾丘丘暴徒
        ///21020201: 火斧丘丘暴徒
        ///21020202: 火斧丘丘暴徒
        ///21020301: 岩盾丘丘暴徒
        ///21020401: 丘丘霜铠王
        ///21020501: 丘丘岩盔王
        ///21020601: 冰盾丘丘暴徒
        ///21020701: 雷斧丘丘暴徒
        ///21020703: 雷斧丘丘暴徒
        ///21020801: 丘丘雷兜王
        ///20010101: 草史莱姆
        ///20010201: 大型草史莱姆
        ///20010202: 大型草史莱姆
        ///20010301: 风史莱姆
        ///20010401: 大型风史莱姆
        ///20010403: 大型风史莱姆
        ///29010101: 裂空的魔龙
        ///29010102: 裂空的魔龙
        ///29010103: 裂空的魔龙
        ///29010104: 裂空的魔龙
        ///29020101: 北风的王狼，奔狼的领主
        ///29020102: 北风的王狼，奔狼的领主
        ///29030103: 「公子」
        ///29030106: 「公子」
        ///29040101: 若陀龙王
        ///29040102: 若陀龙王
        ///29040103: 若陀龙王
        ///29040104: 若陀龙王
        ///290401 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Monster {
            get {
                return ResourceManager.GetString("Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本名：{0}
        ///更新时间：{1}
        ///更新内容：
        ///{2}
        ///--------------------------------------------
        ///是否查看更新？选择否将不再提醒该版本。 的本地化字符串。
        /// </summary>
        internal static string NewVersionInfo {
            get {
                return ResourceManager.GetString("NewVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1: (test)蒙德城主$UNRELEASED
        ///2: (test)哥哥$UNRELEASED
        ///3: (test)妹妹$UNRELEASED
        ///4: (test)塔主$UNRELEASED
        ///5: (test)仆人$UNRELEASED
        ///6: (test)东北村长$UNRELEASED
        ///7: (test)西北村长$UNRELEASED
        ///8: (test)西南村长$UNRELEASED
        ///9: (test)正南村长$UNRELEASED
        ///10: (test)晖哥$UNRELEASED
        ///11: (test)果酱$UNRELEASED
        ///12: (test)汪汪1$UNRELEASED
        ///13: (test)汪汪2$UNRELEASED
        ///14: (test)汪汪3$UNRELEASED
        ///15: (test)汪汪4$UNRELEASED
        ///21: (test)卫兵$UNRELEASED
        ///22: (test)卫兵$UNRELEASED
        ///23: (test)卫兵$UNRELEASED
        ///24: (test)卫兵$UNRELEASED
        ///25: (test)路人$UNRELEASED
        ///26: (te [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string NPC {
            get {
                return ResourceManager.GetString("NPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. 填写正确的UID\n2. 向玩家发送验证码\n3. 输入正确的验证码\n4. 连接\n5. 享受 的本地化字符串。
        /// </summary>
        internal static string OpenCommandHelp {
            get {
                return ResourceManager.GetString("OpenCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 369101: 翠目猫
        ///369102: 北地犬
        ///369103: 野林猪
        ///369104: 蓝翎鹭
        ///369105: 巡林犬
        ///369106: 柴犬
        ///369107: 黑背猎犬
        ///369108: 北地猫
        ///369109: 虎纹猫
        ///369110: 警长猫
        ///368101: 枫原万叶
        ///368102: 烟绯
        ///368103: 优菈
        ///368104: 琴
        ///368105: 丽莎
        ///368106: 芭芭拉
        ///368107: 凯亚
        ///368108: 迪卢克
        ///368109: 雷泽
        ///368110: 安柏
        ///368111: 温迪
        ///368112: 香菱
        ///368113: 北斗
        ///368114: 行秋
        ///368115: 魈
        ///368116: 凝光
        ///368117: 可莉
        ///368118: 钟离
        ///368119: 菲谢尔
        ///368120: 班尼特
        ///368121: 达达利亚
        ///368122: 诺艾尔
        ///368123: 七七
        ///368124: 重云
        ///368125: 甘雨
        ///368126: 阿贝多
        ///368127: 迪奥娜
        ///368128: 莫娜
        ///368129: 刻晴
        ///368130: 砂糖
        ///368131: 辛焱
        ///3 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Ornament {
            get {
                return ResourceManager.GetString("Ornament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要设置的权限不能为空！ 的本地化字符串。
        /// </summary>
        internal static string PermissionCannotBeEmpty {
            get {
                return ResourceManager.GetString("PermissionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *
        ///player.*
        ///player.**
        ///server.*
        ///server.**
        ///player.changescene
        ///player.clearinv
        ///player.enterdungeon
        ///player.give
        ///player.giveall
        ///player.giveart
        ///player.givechar
        ///player.godmode
        ///player.heal
        ///player.killcharacter
        ///player.resetconstellation
        ///player.setfetterlevel
        ///player.setstats
        ///player.settalent
        ///player.setworldlevel
        ///player.teleport
        ///player.tpall
        ///player.weather
        ///server.broadcast
        ///server.coop
        ///server.drop
        ///server.kick
        ///server.killall
        ///server.reload
        ///server.resetshop
        ///server.sendmail
        ///server.sendmessage        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 347: 阅读占坑$HIDDEN
        ///348: 猫尾酒馆留言板$HIDDEN
        ///349: 蒙德百货订货版$HIDDEN
        ///350: 捕风的异乡人$HIDDEN
        ///351: 流浪者的足迹
        ///362: 苹果教学$HIDDEN
        ///352: 鸟瞰风物
        ///353: 异常的权柄
        ///361: 风魔龙飞过$HIDDEN
        ///355: 林间相会
        ///354: 随风而来的骑士
        ///360: 与轻风同行
        ///356: 自由之都
        ///357: 龙灾
        ///358: 西风骑士团
        ///359: (test)蒙德与三地城$HIDDEN
        ///306: 昔日的风
        ///307: 骑士的现场教习
        ///308: 书页里的电火花
        ///309: (test)蒙德之围$HIDDEN
        ///310: 招募新伙伴
        ///311: (test)一阶段结束$HIDDEN
        ///312: (test)丽莎地城，丽莎书本奖励$HIDDEN
        ///363: (test)控制第一幕开始的隐藏任务$HIDDEN
        ///370: 阴影下的蒙德
        ///371: 不期而遇
        ///372: 那个绿色的家伙
        ///373: 听凭风引
        ///374: 温迪的计划
        ///375: 温迪的新计划
        ///376: 逃亡
        ///377: 幕后谈话
        ///20101:  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Quest {
            get {
                return ResourceManager.GetString("Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先连接到支持[OpenCommand]的服务器 的本地化字符串。
        /// </summary>
        internal static string RequireOpenCommandTip {
            get {
                return ResourceManager.GetString("RequireOpenCommandTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 : BigWorld_LevelStreaming
        ///2 : BigWorld_LevelStreaming
        ///3 : BigWorld_LevelStreaming
        ///4 : LostParadise_LevelStreaming
        ///5 : AbyssalPalace_LevelStreaming
        ///6 : TheChasm_LevelStreaming
        ///7 : MichiaeMatsuri_LevelStreaming
        ///20008: 深入狼之殿
        ///20008: 丘丘人大本营(test)
        ///20008: 丘丘人巢穴(test)
        ///20007: 小岩洞据点(test)
        ///20007: 小岩洞据点(test)
        ///20007: 小岩洞秘境(test)
        ///20006: 遗迹遇险点(test)
        ///20006: 丘丘人小据点(test)
        ///20006: 丘丘人大据点(test)
        ///1006: 密林、废墟与龙之泪
        ///1017: 壶中天
        ///1019: 洞天云海地城玩法测试(test)
        ///1011: 角色战斗测试(test)
        ///50002: 低温关卡白盒(test)
        ///1001: 移动平台性能测试(test)
        ///50 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载设置时异常： 的本地化字符串。
        /// </summary>
        internal static string SettingLoadError {
            get {
                return ResourceManager.GetString("SettingLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置时异常： 的本地化字符串。
        /// </summary>
        internal static string SettingSaveError {
            get {
                return ResourceManager.GetString("SettingSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空！ 的本地化字符串。
        /// </summary>
        internal static string UsernameCannotBeEmpty {
            get {
                return ResourceManager.GetString("UsernameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11101: 无锋剑
        ///11201: 银剑
        ///11301: 冷刃
        ///11302: 黎明神剑
        ///11303: 旅行剑
        ///11304: 暗铁剑
        ///11305: 吃虎鱼刀
        ///11306: 飞天御剑
        ///11401: 西风剑
        ///11402: 笛剑
        ///11403: 祭礼剑
        ///11404: 宗室长剑
        ///11405: 匣里龙吟
        ///11406: 试作斩岩
        ///11407: 铁蜂刺
        ///11408: 黑岩长剑
        ///11409: 黑剑
        ///11410: 暗巷闪光
        ///11412: 降临之剑
        ///11413: 腐殖之剑
        ///11414: 天目影打刀
        ///11415: 辰砂之纺锤
        ///11501: 风鹰剑
        ///11502: 天空之刃
        ///11503: 苍古自由之誓
        ///11504: 斫峰之刃
        ///11505: 磐岩结绿
        ///11509: 雾切之回光
        ///11510: 波乱月白经津
        ///12101: 训练大剑
        ///12201: 佣兵重剑
        ///12301: 铁影阔剑
        ///12302: 沐浴龙血的剑
        ///12303: 白铁大剑
        ///12304: 石英大剑
        ///12305: 以理服人
        ///12306: 飞天大御剑
        ///12401: 西风大剑
        ///12402: 钟剑
        ///12403: 祭礼大剑        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11301:blue
        ///11302:blue
        ///11303:blue
        ///11304:blue
        ///11305:blue
        ///11306:blue
        ///11401:purple
        ///11402:purple
        ///11403:purple
        ///11404:purple
        ///11405:purple
        ///11406:purple
        ///11407:purple
        ///11408:purple
        ///11409:purple
        ///11410:purple
        ///11411:purple
        ///11412:purple
        ///11413:purple
        ///11414:purple
        ///11415:purple
        ///11501:yellow
        ///11502:yellow
        ///11503:yellow
        ///11504:yellow
        ///11505:yellow
        ///11506:yellow
        ///11507:yellow
        ///11508:yellow
        ///11509:yellow
        ///11510:yellow
        ///12301:blue
        ///12302:blue
        ///12303:blue
        ///12304:blue
        ///12305:blue
        ///12306:blue
        ///12401:purple
        ///1240 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WeaponColor {
            get {
                return ResourceManager.GetString("WeaponColor", resourceCulture);
            }
        }
    }
}
