//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrasscutterTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrasscutterTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 10001: HP
        ///10002: HP Percentage
        ///10003: ATK
        ///10004: ATK Percentage
        ///10005: DEF
        ///10006: DEF Percentage
        ///10007: Energy Recharge
        ///10008: Elemental Mastery
        ///10009: Pyro RES
        ///10010: Electro RES
        ///10011: Cryo RES
        ///10012: Hydro RES
        ///10013: Anemo RES
        ///10014: Geo RES
        ///10015: Dendro RES
        ///12001: ATK
        ///13001: HP
        ///13002: HP Percentage
        ///13003: ATK
        ///13004: ATK Percentage
        ///13005: DEF
        ///13006: DEF Percentage
        ///13007: CRIT Rate
        ///13008: CRIT DMG
        ///13009: Healing Bonus
        ///13010: Elemental Mastery
        ///14001: HP
        ///15001: HP
        ///15002: HP Perc [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ArtifactMainAttribution {
            get {
                return ResourceManager.GetString("ArtifactMainAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20:Deepwood Memories
        ///21:Gilded Dreams
        ///51:Resolution of Sojourner
        ///52:Brave Heart
        ///53:Defender&apos;s Will
        ///54:Tiny Miracle
        ///55:Berserker
        ///56:Martial Artist
        ///57:Instructor
        ///58:Gambler
        ///59:The Exile
        ///60:Adventurer
        ///61:Lucky Dog
        ///62:Scholar
        ///63:Traveling Doctor
        ///71:Blizzard Strayer
        ///72:Thundersoother
        ///73:Lavawalker
        ///74:Maiden Beloved
        ///75:Gladiator&apos;s Finale
        ///76:Viridescent Venerer
        ///77:Wanderer&apos;s Troupe
        ///78:Glacier and Snowfield
        ///79:Thundering Fury
        ///80:Crimson Witch of Flames
        ///81:Noblesse Oblige
        ///82:Bloodstained Ch [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ArtifactSets {
            get {
                return ResourceManager.GetString("ArtifactSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 101021: HP+24
        ///101022: HP+30
        ///201021: HP+50
        ///201022: HP+61
        ///201023: HP+72
        ///301021: HP+100
        ///301022: HP+115
        ///301023: HP+129
        ///301024: HP+143
        ///401021: HP+167
        ///401022: HP+191
        ///401023: HP+215
        ///401024: HP+239
        ///501021: HP+209
        ///501022: HP+239
        ///501023: HP+269
        ///501024: HP+299
        ///101031: HP Percentage+1.2%
        ///101032: HP Percentage+1.5%
        ///201031: HP Percentage+1.6%
        ///201032: HP Percentage+2.0%
        ///201033: HP Percentage+2.3%
        ///301031: HP Percentage+2.4%
        ///301032: HP Percentage+2.8%
        ///301033: HP Percentage+3.2%
        ///301034: HP Percentage [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ArtifactSubAttribution {
            get {
                return ResourceManager.GetString("ArtifactSubAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] AvatarStats {
            get {
                object obj = ResourceManager.GetObject("AvatarStats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Colors {
            get {
                object obj = ResourceManager.GetObject("Colors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 God Mode
        ////prop god on
        ///NoStamina
        ////prop ns on
        ///Unlimited Energy
        ////prop ue on
        ///Level up to 60
        ////give 102 x1880200
        ///Set World Level
        ////prop wl 8
        ///Unlock Map
        ////prop unlockmap 1
        ///Unlock The Tower
        ////prop ut 12
        ///Set BattlePass Level
        ////prop bp 50
        ///Set Friendship Level
        ////setfetterlevel 10
        ///Heal
        ////h
        ///Suicide
        ////kill 0
        ///Charge Energy
        ////spawn 2008 25
        ///Where am I?
        ////pos
        ///Give me ALL!
        ////give all x9999 lv90 c6 r5
        ///10k Intertwined Fates
        ////give 223 x10000
        ///10k Acquaint Fates
        ////give 224 x10000
        ///100k Primogem
        ////give 201 x1000 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string CustomCommands {
            get {
                return ResourceManager.GetString("CustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Dungeons
        ///1:Level_KaeyaTutorialMission01
        ///2:Level_KaeyaTutorialMission01
        ///3:Level_KaeyaTutorialMission01
        ///4:PlotLevel_BarbaraMission02_Xyd
        ///5:PlotLevel_BarbaraMission02_Xyd
        ///6:PlotLevel_BarbaraMission02_Xyd
        ///7:Level_UCDungeon01
        ///8:Level_UCDungeon01
        ///9:Level_UCDungeon01
        ///10:Level_PFDungeon01
        ///11:Level_FCdungeon_Kettle01
        ///12:Level_Wisdom03
        ///13:Level_Gameplay_Test
        ///15:TestLevel_Cold_LYX
        ///16:ClimbTest1
        ///17:TestLevel_Battle_CLX
        ///18:Level_PowerCharge_Test
        ///19:Level_CycleDungeon02_Normal
        ///20:Level_CycleDungeon02_Normal
        ///21:Level_C [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Dungeons {
            get {
                return ResourceManager.GetString("Dungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 007:Beginners&apos; wish
        ///008:Wanderlust Invocation
        ///009:Ballad in Goblets
        ///010:Dawn Pilgrimage
        ///011:Grace of Southwind
        ///012:Bane of All Evil
        ///013:Epitome Invocation
        ///015:Sparkling Steps
        ///016:Beginners&apos; wish
        ///017:Wanderlust Invocation
        ///018:Sparkling Steps
        ///019:Ballad in Goblets
        ///020:Epitome Invocation
        ///021:Epitome Invocation
        ///022:Wanderlust Invocation
        ///023:Farewell of Snezhnaya
        ///024:Gentry of Hermitage
        ///027:Secretum Secretorum
        ///028:Adrift in the Harbor
        ///031:Invitation to Mundane Life
        ///032:Dance of Lanterns
        ///033: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string GachaBennerPrefab {
            get {
                return ResourceManager.GetString("GachaBennerPrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GrasscutterTools 的本地化字符串。
        /// </summary>
        public static string GrasscutterTools {
            get {
                return ResourceManager.GetString("GrasscutterTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon IconGrasscutter {
            get {
                object obj = ResourceManager.GetObject("IconGrasscutter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ImgGrasscutter {
            get {
                object obj = ResourceManager.GetObject("ImgGrasscutter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ImgHome {
            get {
                object obj = ResourceManager.GetObject("ImgHome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ImgSupport {
            get {
                object obj = ResourceManager.GetObject("ImgSupport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 // VirtualItems
        ///101:Character EXP
        ///102:Adventure EXP
        ///105:Companionship EXP
        ///106:Original Resin
        ///107:Story Key
        ///108:[CHS] - (test)天体推演
        ///109:Fading Star&apos;s Might
        ///110:Fading Star&apos;s Essence
        ///111:Glimmering Essence
        ///112:Warm Essence
        ///113:Miraculous Essence
        ///114:Iron Coin
        ///115:Peace Talisman
        ///116:Festive Fever
        ///117:Veneficus Sigil
        ///118:Festive Tour Ticket
        ///119:Peculiar Collab Coupon
        ///120:Heart of the Spring
        ///121:Trust
        ///122:Fractured Fruit Data
        ///123:Windtrace Coins
        ///124:Shiny Flotsam
        ///125:Mini &quot;Harpastum&quot;
        ///126:E [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // MONSTER_NONE
        ///
        ///
        ///// MONSTER_ORDINARY
        ///20010101:Dendro Slime
        ///20010201:Large Dendro Slime
        ///20010202:Large Dendro Slime
        ///20010301:Anemo Slime
        ///20010302:Anemo Slime
        ///20010401:Large Anemo Slime
        ///20010402:Large Anemo Slime
        ///20010403:Large Anemo Slime
        ///20010501:Electro Slime
        ///20010502:Electro Slime
        ///20010601:Large Electro Slime
        ///20010602:Large Electro Slime
        ///20010604:Large Electro Slime
        ///20010701:Mutant Electro Slime
        ///20010702:Mutant Electro Slime
        ///20010703:Mutant Electro Slime
        ///20010801:Cryo Slime
        ///20010802: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Monsters {
            get {
                return ResourceManager.GetString("Monsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *
        ///player.*
        ///player.**
        ///server.*
        ///server.**
        ///permission
        ///player.clearinv
        ///player.clearinv.others
        ///player.enterdungeon
        ///player.enterdungeon.others
        ///player.give
        ///player.give.others
        ///player.heal
        ///player.heal.others
        ///player.killcharacter
        ///player.killcharacter.others
        ///player.quest
        ///player.quest.others
        ///player.resetconstellation
        ///player.resetconstellation.others
        ///player.setfetterlevel
        ///player.setfetterlevel.others
        ///player.setprop
        ///player.setprop.others
        ///player.setstats
        ///player.setstats.others
        ///player.settalent
        ///p [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30302:Goddess Statue Unlocked - [N/A] 362713143
        ///30303:Goddess Statue Unlocked - [N/A] 715511863
        ///30304:Goddess Statue Unlocked - [N/A] 163018255
        ///30305:Goddess Statue Unlocked - [N/A] 3694648119
        ///30306:Goddess Statue Unlocked - [N/A] 3223799591
        ///30307:Goddess Statue Unlocked - [N/A] 1232757671
        ///30308:Goddess Statue Unlocked - [N/A] 3056513767
        ///30309:Goddess Statue Unlocked - [N/A] 2426653367
        ///30310:Goddess Statue Unlocked - [N/A] 2003131071
        ///30311:Goddess Statue Unlocked - [N/A] 105277231
        ///30312:Goddess St [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Scenes
        ///
        ///
        ///// SCENE_NONE
        ///
        ///
        ///// SCENE_WORLD
        ///1:BigWorld_LevelStreaming
        ///2:BigWorld_LevelStreaming
        ///3:BigWorld_LevelStreaming
        ///4:LostParadise_LevelStreaming
        ///5:AbyssalPalace_LevelStreaming
        ///6:TheChasm_LevelStreaming
        ///7:MichiaeMatsuri_LevelStreaming
        ///9:DreamIsland_LevelStreaming
        ///1002:ClimbTest2
        ///1003:TheBigWorld
        ///1030:TestIntercept_LiYue
        ///50020:ClimbTest1
        ///50069:TestLevel_ClimbBox
        ///50071:TestWorld_APA_ZQQ
        ///50073:PerformanceTest_LevelStreaming
        ///
        ///
        ///// SCENE_DUNGEON
        ///1001:ClimbTest1
        ///1006:Level_PFDungeon01
        ///1011:Level_Gameplay_Test [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Scenes {
            get {
                return ResourceManager.GetString("Scenes", resourceCulture);
            }
        }
    }
}
