//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrasscutterTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrasscutterTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 80001:风与异乡人 - 使用风元素吹散一株蒲公英。
        ///80002:千嶂万仞 - 掌握「岩」的元素力。
        ///80003:流水叮咛 - 集齐全套《清泉之心》。
        ///80004:神戟狂言凌云霄 - 集齐全套《神霄折戟录》。
        ///80005:醉客与狼的相遇 - 集齐全套《醉客轶事》。
        ///80006:清泉、白马与月光 - 集齐全套《竹林月夜》。
        ///80007:人铸赋形 - 锻造一把四星武器。
        ///80008:生存专家 - 掌握10种菜肴的制作方法。
        ///80009:生存专家 - 掌握20种菜肴的制作方法。
        ///80010:生存专家 - 掌握40种菜肴的制作方法。
        ///80011:星级大厨 - 10个料理食谱达到熟练。
        ///80012:星级大厨 - 20个料理食谱达到熟练。
        ///80013:星级大厨 - 40个料理食谱达到熟练。
        ///80014:如日方升的旅程 - 角色首次突破至2阶。
        ///80015:如日方升的旅程 - 角色首次突破至4阶。
        ///80016:如日方升的旅程 - 角色首次突破至6阶。
        ///80017:百炼千锤 - 将一个武器突破至2阶。
        ///80018:百炼千锤 - 将一个武器突破至4阶。
        ///80019:百炼千锤 - 将一个武器 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Achievement {
            get {
                return ResourceManager.GetString("Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //［Activity ids-3.8 by dplek］
        ///// Activity
        ///2001:1.1未归的熄星
        ///2002:1.3海灯节
        ///2003:1.4风花节
        ///2004:1.5导能原盘-诸论
        ///2005:1.6盛夏！海岛？大冒险！
        ///2006:2.0谒索雷痕
        ///2007:2.1韶光抚月
        ///2008:2.2雾海悬谜境
        ///2009:2.3皑尘与雪影
        ///2010:2.4飞彩镌流年
        ///2011:2.5三界路飨祭
        ///2012:2.6堇庭华彩
        ///2013:2.7荒梦藏虞渊
        ///2014:2.8远海诗夏游纪
        ///2015:3.0雕琢童心
        ///2016:3.1杯中遥吟之歌
        ///2017:3.2智巧灵蕈大竞逐
        ///2018:3.3秋津森夜试胆会
        ///2019:3.4磬弦奏华夜
        ///2020:3.5风花的呼吸
        ///2021:3.6盛典与慧业
        ///2022:3.7决战！召唤之巅！
        ///2023:3.8清夏！乐园？大秘境！
        ///2024:4.0机枢巧物前哨战
        ///// 1.0
        ///1001:海灯节
        ///5001:元素烘炉（test）
        ///5002:且试身手
        ///5003:百货奇货
        ///// 1.1
        ///5004:映天之章
        ///5005:元素烘炉
        ///5006:佳 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20412:迷误者之灯
        ///20413:迷误者之灯
        ///20422:翠蔓的智者
        ///20423:翠蔓的智者
        ///20432:月桂的宝冠
        ///20433:月桂的宝冠
        ///20442:迷宫的游人
        ///20443:迷宫的游人
        ///20452:贤智的定期
        ///20453:贤智的定期
        ///20513:迷误者之灯
        ///20514:迷误者之灯
        ///20523:翠蔓的智者
        ///20524:翠蔓的智者
        ///20533:月桂的宝冠
        ///20534:月桂的宝冠
        ///20543:迷宫的游人
        ///20544:迷宫的游人
        ///20553:贤智的定期
        ///20554:贤智的定期
        ///21412:如蜜的终宴
        ///21413:如蜜的终宴
        ///21422:裁断的翎羽
        ///21423:裁断的翎羽
        ///21432:沙王的投影
        ///21433:沙王的投影
        ///21442:梦中的铁花
        ///21443:梦中的铁花
        ///21452:沉金的岁月
        ///21453:沉金的岁月
        ///21513:如蜜的终宴
        ///21514:如蜜的终宴
        ///21523:裁断的翎羽
        ///21524:裁断的翎羽
        ///21533:沙王的投影
        ///21534:沙王的投影
        ///21543:梦中的铁花
        ///21544:梦中的铁花
        ///21553:沉金的岁月
        ///21554 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Artifact {
            get {
                return ResourceManager.GetString("Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20:深林的记忆
        ///21:饰金之梦
        ///27:沙上楼阁史话
        ///28:乐园遗落之花
        ///29:水仙之梦
        ///30:花海甘露之光
        ///31:逐影猎人
        ///32:黄金剧团
        ///51:行者之心
        ///52:勇士之心
        ///53:守护之心
        ///54:奇迹
        ///55:战狂
        ///56:武人
        ///57:教官
        ///58:赌徒
        ///59:流放者
        ///60:冒险家
        ///61:幸运儿
        ///62:学士
        ///63:游医
        ///71:冰风迷途的勇士
        ///72:平息鸣雷的尊者
        ///73:渡过烈火的贤人
        ///74:被怜爱的少女
        ///75:角斗士的终幕礼
        ///76:翠绿之影
        ///77:流浪大地的乐团
        ///78:冰之川与雪之砂
        ///79:如雷的盛怒
        ///80:炽烈的炎之魔女
        ///81:昔日宗室之仪
        ///82:染血的骑士道
        ///83:祭火之人
        ///84:祭水之人
        ///85:祭雷之人
        ///86:祭风之人
        ///87:祭冰之人
        ///88:悠古的磐岩
        ///89:逆飞的流星
        ///90:沉沦之心
        ///91:千岩牢固
        ///92:苍白之火
        ///93:追忆之注连
        ///94:绝缘之旗印
        ///95:华馆梦醒形骸记
        ///96:海染砗磲
        ///97:辰砂往生录
        ///98:来歆余响
        ///99:高天的风之主 的本地化字符串。
        /// </summary>
        internal static string ArtifactCat {
            get {
                return ResourceManager.GetString("ArtifactCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10001: 生命值
        ///10002: 生命值百分比
        ///10003: 攻击力
        ///10004: 攻击力百分比
        ///10005: 防御力
        ///10006: 防御力百分比
        ///10007: 元素充能效率
        ///10008: 元素精通
        ///10009: 火元素抗性
        ///10010: 雷元素抗性
        ///10011: 冰元素抗性
        ///10012: 水元素抗性
        ///10013: 风元素抗性
        ///10014: 岩元素抗性
        ///10015: 草元素抗性
        ///12001: 攻击力
        ///13001: 生命值
        ///13002: 生命值百分比
        ///13003: 攻击力
        ///13004: 攻击力百分比
        ///13005: 防御力
        ///13006: 防御力百分比
        ///13007: 暴击率
        ///13008: 暴击伤害
        ///13009: 治疗加成
        ///13010: 元素精通
        ///14001: 生命值
        ///15001: 生命值
        ///15002: 生命值百分比
        ///15003: 攻击力
        ///15004: 攻击力百分比
        ///15005: 防御力
        ///15006: 防御力百分比
        ///15007: 元素精通
        ///15008: 火元素伤害加成
        ///15009: 雷元素伤害加成
        ///15010: 冰元素伤害加成
        ///15011:  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ArtifactMainAttribution {
            get {
                return ResourceManager.GetString("ArtifactMainAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空之杯,死之羽,理之冠,生之花,时之沙 的本地化字符串。
        /// </summary>
        internal static string ArtifactPartLabels {
            get {
                return ResourceManager.GetString("ArtifactPartLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 101021: 生命值+24
        ///101022: 生命值+30
        ///201021: 生命值+50
        ///201022: 生命值+61
        ///201023: 生命值+72
        ///301021: 生命值+100
        ///301022: 生命值+115
        ///301023: 生命值+129
        ///301024: 生命值+143
        ///401021: 生命值+167
        ///401022: 生命值+191
        ///401023: 生命值+215
        ///401024: 生命值+239
        ///501021: 生命值+209
        ///501022: 生命值+239
        ///501023: 生命值+269
        ///501024: 生命值+299
        ///101031: 生命值百分比+1.2%
        ///101032: 生命值百分比+1.5%
        ///201031: 生命值百分比+1.6%
        ///201032: 生命值百分比+2.0%
        ///201033: 生命值百分比+2.3%
        ///301031: 生命值百分比+2.4%
        ///301032: 生命值百分比+2.8%
        ///301033: 生命值百分比+3.2%
        ///301034: 生命值百分比+3.5%
        ///401031: 生命值百分比+3.3%
        ///401032: 生命值百分比+3.7 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ArtifactSubAttribution {
            get {
                return ResourceManager.GetString("ArtifactSubAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除？ 的本地化字符串。
        /// </summary>
        internal static string AskConfirmDeletion {
            get {
                return ResourceManager.GetString("AskConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1002:神里绫华
        ///1003:琴
        ///1005:男主
        ///1006:丽莎
        ///1007:女主
        ///1014:芭芭拉
        ///1015:凯亚
        ///1016:迪卢克
        ///1020:雷泽
        ///1021:安柏
        ///1022:温迪
        ///1023:香菱
        ///1024:北斗
        ///1025:行秋
        ///1026:魈
        ///1027:凝光
        ///1029:可莉
        ///1030:钟离
        ///1031:菲谢尔
        ///1032:班尼特
        ///1033:达达利亚
        ///1034:诺艾尔
        ///1035:七七
        ///1036:重云
        ///1037:甘雨
        ///1038:阿贝多
        ///1039:迪奥娜
        ///1041:莫娜
        ///1042:刻晴
        ///1043:砂糖
        ///1044:辛焱
        ///1045:罗莎莉亚
        ///1046:胡桃
        ///1047:枫原万叶
        ///1048:烟绯
        ///1049:宵宫
        ///1050:托马
        ///1051:优菈
        ///1052:雷电将军
        ///1053:早柚
        ///1054:珊瑚宫心海
        ///1055:五郎
        ///1056:九条裟罗
        ///1057:荒泷一斗
        ///1058:八重神子
        ///1059:鹿野院平藏
        ///1060:夜兰
        ///1062:埃洛伊
        ///1063:申鹤
        ///1064:云堇
        ///1065:久岐忍
        ///1066:神里绫人
        ///1067:柯莱
        ///1068 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1002:5
        ///1003:5
        ///1005:5
        ///1006:4
        ///1007:5
        ///1014:4
        ///1015:4
        ///1016:5
        ///1020:4
        ///1021:4
        ///1022:5
        ///1023:4
        ///1024:4
        ///1025:4
        ///1026:5
        ///1027:4
        ///1029:5
        ///1030:5
        ///1031:4
        ///1032:4
        ///1033:5
        ///1034:4
        ///1035:5
        ///1036:4
        ///1037:5
        ///1038:5
        ///1039:4
        ///1041:5
        ///1042:5
        ///1043:4
        ///1044:4
        ///1045:4
        ///1046:5
        ///1047:5
        ///1048:4
        ///1049:5
        ///1050:4
        ///1051:5
        ///1052:5
        ///1053:4
        ///1054:5
        ///1055:4
        ///1056:4
        ///1057:5
        ///1058:5
        ///1059:4
        ///1060:5
        ///1061:4
        ///1062:5
        ///1063:5
        ///1064:4
        ///1065:4
        ///1066:5
        ///1067:4
        ///1068:4
        ///1069:5
        ///1070:5
        ///1071:5
        ///1072:4
        ///1073:5
        ///1074:4
        ///1075:5
        ///1076:4
        ///1077:4
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AvatarColor {
            get {
                return ResourceManager.GetString("AvatarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] AvatarStats {
            get {
                object obj = ResourceManager.GetObject("AvatarStats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Banners {
            get {
                object obj = ResourceManager.GetObject("Banners", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 浏览器打开失败，你可以通过以下链接手动访问： 的本地化字符串。
        /// </summary>
        internal static string BrowserOpenFailedTip {
            get {
                return ResourceManager.GetString("BrowserOpenFailedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查到新版本 的本地化字符串。
        /// </summary>
        internal static string CheckToNewVersion {
            get {
                return ResourceManager.GetString("CheckToNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无,晴天,多云,雨天,雷暴,雪天,雾天 的本地化字符串。
        /// </summary>
        internal static string ClimateType {
            get {
                return ResourceManager.GetString("ClimateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒后可重发 的本地化字符串。
        /// </summary>
        internal static string CodeResendTip {
            get {
                return ResourceManager.GetString("CodeResendTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送中... 的本地化字符串。
        /// </summary>
        internal static string CodeSending {
            get {
                return ResourceManager.GetString("CodeSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令内容不能为空 的本地化字符串。
        /// </summary>
        internal static string CommandContentCannotBeEmpty {
            get {
                return ResourceManager.GetString("CommandContentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到该命令 的本地化字符串。
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令标签不能为空 的本地化字符串。
        /// </summary>
        internal static string CommandTagCannotBeEmpty {
            get {
                return ResourceManager.GetString("CommandTagCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现在你可以远程执行命令了哦！ 的本地化字符串。
        /// </summary>
        internal static string ConnectedTip {
            get {
                return ResourceManager.GetString("ConnectedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无敌
        ////prop god on
        ///无限体力
        ////prop ns on
        ///无限能量
        ////prop ue on
        ///冒险等阶升60级
        ////give 102 x1880200
        ///尘歌壶信任值升到10级
        ////give 121 x10900
        ///设置世界等级8
        ////prop wl 8
        ///点亮地图
        ////prop unlockmap 1
        ///一键解锁深渊12层
        ////prop ut 12
        ///设置纪行等级50
        ////prop bp 50
        ///设置好感等级10
        ////setfetterlevel 10
        ///回血
        ////h
        ///自杀
        ////kill 0
        ///全队充能
        ////spawn 2008 x25
        ///查看坐标
        ////pos
        ///获取全部物品
        ////give all x9999 lv90 c6 r5 sl10
        ///一万纠缠
        ////give 223 x10000
        ///一万相遇
        ////give 224 x10000
        ///十万原石
        ////give 201 x100000
        ///一亿摩拉
        ////give 202 x100000000
        ///重载配置
        ////reload
        ///重登
        ////kick
        ///清空当前角色命之座(需重登)
        ////resetconst
        ///清空全部角色命之座(需重登)
        ////re [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CustomCommands {
            get {
                return ResourceManager.GetString("CustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1:[测试]空画面
        ///2:[测试]空画面
        ///3:[疑似剧情]风起地七天神像激活
        ///4:未知秘境内某门开启
        ///5:未知秘境内某门开启
        ///6:无画面(UI会闪一下)
        ///7:未知区域画面旋转
        ///8:进入风龙废墟秘境
        ///9:达达乌帕谷剑屏障解锁
        ///200201:[剧情]蒙德主线特瓦林最后战斗  秘境ID:20018(测试)或20025(正式)
        ///10:风龙废墟解除三层封印1
        ///11:风龙废墟解除三层封印2
        ///12:风龙废墟解除三层封印3
        ///13:秘境奖励领取时
        ///14:未知区域画面旋转
        ///15:不明地下视角
        ///16:不明地下视角
        ///17:忍冬之树普通
        ///18:忍冬之树形态1
        ///19:忍冬之树1升级2
        ///20:忍冬之树形态2
        ///21:忍冬之树2升级3
        ///22:雪山冰本进入时
        ///23:不明地下视角
        ///24:不明地下视角
        ///25:稻妻神樱树远景
        ///26:[世界任务]神樱大祓净化进度1
        ///27:[世界任务]神樱大祓净化进度2
        ///28:[世界任务]神樱大祓净化进度3
        ///29:[世界任务]神樱大祓净化进度4
        ///30:[世界任务]神樱大祓净化进度5
        ///31:稻妻荒海机关解锁
        ///32:稻妻八酝岛阵代屋敷秘境解锁
        ///33:稻妻清籁岛木 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Cutscene {
            get {
                return ResourceManager.GetString("Cutscene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1:深入狼之殿
        ///2:丘丘人大本营(test)
        ///3:丘丘人巢穴(test)
        ///4:小岩洞据点(test)
        ///5:小岩洞据点(test)
        ///6:小岩洞秘境(test)
        ///7:遗迹遇险点(test)
        ///8:丘丘人小据点(test)
        ///9:丘丘人大据点(test)
        ///10:密林、废墟与龙之泪
        ///11:壶中天
        ///12:洞天云海地城玩法测试(test)
        ///13:角色战斗测试(test)
        ///15:低温关卡白盒(test)
        ///16:移动平台性能测试(test)
        ///17:战斗性能测试(test)
        ///18:电桩电源白盒(test)
        ///19:圣遗物新因子测试关卡3(test)
        ///20:圣遗物新因子测试关卡1(test)
        ///21:圣遗物新因子测试关卡2(test)
        ///24:黑夜循环地城(test)
        ///25:关卡玩法白盒CX(test)
        ///26:机关玩法白盒(test)
        ///27:怪物元素对抗地城(test)
        ///28:地城功能白盒测试(test)
        ///29:守护玩法白盒测试(test)
        ///30:夺回宝物
        ///31:岩元素白盒测试(test)
        ///32:蒙德圣遗物挑战1白盒测试(test)
        ///33:爬塔丘丘人模板(test)
        ///34:云海白 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Dungeon {
            get {
                return ResourceManager.GetString("Dungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入不能为空！ 的本地化字符串。
        /// </summary>
        internal static string EmptyInputTip {
            get {
                return ResourceManager.GetString("EmptyInputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 007:初行者推荐祈愿
        ///008:奔行世间
        ///009:杯装之诗
        ///010:黎明巡礼
        ///011:南风之眷
        ///012:靖妖傩舞
        ///013:神铸赋形
        ///015:闪焰的驻足
        ///016:初行者推荐祈愿
        ///017:奔行世间
        ///018:闪焰的驻足
        ///019:杯装之诗
        ///020:神铸赋形
        ///021:神铸赋形
        ///022:奔行世间
        ///023:暂别冬都
        ///024:陵薮市朝
        ///027:深秘之息
        ///028:浮生孰来
        ///031:烟火之邀
        ///032:鱼龙灯昼
        ///033:赤团开时
        ///036:杯装之诗
        ///037:暂别冬都
        ///040:陵薮市朝
        ///041:浪涌之瞬
        ///045:叶落风随
        ///048:白鹭之庭
        ///049:焰色天河
        ///052:影寂天下人
        ///053:浮岳虹珠
        ///061:鬼门斗宴
        ///065:出尘入世
        ///071:华紫樱绯
        ///076:苍流踏花
        ///081:素霓伣天
        ///091:巡御蘙荟-提纳里
        ///092:陵薮市朝-钟离
        ///093:神铸赋形-猎人贯虹
        ///097:雳裁冥昭-赛诺
        ///098:杯装之诗-温迪
        ///099:神铸赋形-赤沙终末
        ///0100:翩舞歈莲-妮露
        ///0103:月草的赐慧-纳西妲
        ///0109:余火变相-流浪者
        ///0115:敕诫枢谋-艾尔海森        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GachaBannerTitle {
            get {
                return ResourceManager.GetString("GachaBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 007:初行者推荐祈愿
        ///008:奔行世间
        ///009:杯装之诗
        ///010:黎明巡礼
        ///011:南风之眷
        ///012:靖妖傩舞
        ///013:神铸赋形
        ///015:闪焰的驻足
        ///016:初行者推荐祈愿
        ///017:奔行世间
        ///018:闪焰的驻足
        ///019:杯装之诗
        ///020:神铸赋形
        ///021:神铸赋形
        ///022:奔行世间
        ///023:暂别冬都
        ///024:陵薮市朝
        ///027:深秘之息
        ///028:浮生孰来
        ///031:烟火之邀
        ///032:鱼龙灯昼
        ///033:赤团开时
        ///036:杯装之诗
        ///037:暂别冬都
        ///040:陵薮市朝
        ///041:浪涌之瞬
        ///045:叶落风随
        ///048:白鹭之庭
        ///049:焰色天河
        ///052:影寂天下人
        ///053:浮岳虹珠
        ///061:鬼门斗宴
        ///065:出尘入世
        ///071:华紫樱绯
        ///076:苍流踏花
        ///081:素霓伣天
        ///091:巡御蘙荟-提纳里
        ///092:陵薮市朝-钟离
        ///093:神铸赋形-猎人贯虹
        ///097:雳裁冥昭-赛诺
        ///098:杯装之诗-温迪
        ///099:神铸赋形-赤沙终末
        ///100:翩舞歈莲-妮露
        ///101:深秘之息-阿贝多
        ///102:神铸赋形-圣显绿箭
        ///103:月草的赐慧-纳西妲
        ///104 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GachaBannerPrefab {
            get {
                return ResourceManager.GetString("GachaBannerPrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 机关装置
        ///40000001:蒸汽桶炮
        ///70220032:风车机关
        ///70220033:风车机关02-永动风车机关
        ///70290584:升降铁栅栏0.8倍版-升降铁栅栏
        ///70310300:风元素交互 水方碑
        ///70310301:火元素交互 水方碑
        ///70320001:旋转喷火机关
        ///70320002:单面喷火机关
        ///70320003:地城循环点光源
        ///70330086:雷元素溢出洞口
        ///70330332:沙漠 火元素方碑-沙漠 火元素方碑
        ///70330400:沙漠 雷元素方碑
        ///70330401:沙漠 冰元素方碑
        ///70330402:沙漠 风元素方碑
        ///70330403:沙漠 水元素方碑
        ///70330404:沙漠 草元素方碑
        ///70330405:沙漠 岩元素方碑
        ///70330441:海市蜃楼-火元素方碑
        ///70350001:地城大门01-原始门（废弃）
        ///70350002:地城大门02-地城大门 倒品 大
        ///70350003:地城大门03-地城大门 倒品 小
        ///70350004:升降铁栅栏
        ///70350005:横向机关门
        ///70350006:升降铁栅栏-升降铁栅栏 大
        ///70350007:丘丘人升降 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Gadget {
            get {
                return ResourceManager.GetString("Gadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功! 的本地化字符串。
        /// </summary>
        internal static string GOODImportSuccess {
            get {
                return ResourceManager.GetString("GOODImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否导入  的本地化字符串。
        /// </summary>
        internal static string GOODImportText {
            get {
                return ResourceManager.GetString("GOODImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入GOOD档案 的本地化字符串。
        /// </summary>
        internal static string GOODImportTitle {
            get {
                return ResourceManager.GetString("GOODImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前商品ID与其它商店中的ID存在冲突，请更换其它ID或自动生成ID 的本地化字符串。
        /// </summary>
        internal static string GoodsIDConflictPrompt {
            get {
                return ResourceManager.GetString("GoodsIDConflictPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon IconGrasscutter {
            get {
                object obj = ResourceManager.GetObject("IconGrasscutter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgIconGrasscutter {
            get {
                object obj = ResourceManager.GetObject("ImgIconGrasscutter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgSupport {
            get {
                object obj = ResourceManager.GetObject("ImgSupport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 // 虚拟道具
        ///101:角色经验
        ///102:冒险阅历
        ///105:好感经验
        ///106:原粹树脂
        ///107:传说钥匙
        ///108:(test)天体推演
        ///109:熄星能量
        ///110:熄星精粹
        ///111:微光精粹
        ///112:温暖精粹
        ///113:奇迹精粹
        ///114:铁钱
        ///115:平安玉符
        ///116:节庆热度
        ///117:奇术符
        ///118:庆典巡回券
        ///119:奇趣协力券
        ///120:纯水真心
        ///121:信任值
        ///122:碎果数据
        ///123:迷踪币
        ///124:亮闪闪的漂流物
        ///125:迷你「羽球」
        ///126:神秘齿轮
        ///127:鸣雷霰子
        ///128:鸣雷纯晶
        ///129:弈棋术经验
        ///130:灵妙玉符
        ///131:逐月节节庆热度
        ///132:残悴之式札
        ///133:虚损之拓本
        ///134:朽裂之庚牌
        ///135:踏雪章
        ///136:克险章
        ///137:逢福玉符
        ///138:完璧玉符
        ///139:降魔玉符
        ///140:幽蕴砺石
        ///141:花簇簇的漂流物
        ///142:战策碎珀
        ///143:巧思手记
        ///144:随想草稿
        ///145:古铁钱
        ///146:牌手经验
        ///147:节庆热度
        ///148:营业收入
        ///149:可用资金
        ///150:巧策灵感
        ///151:蘑菇宝钱 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将邮件发送给所有人在当前(v1.4.2)或更早版本可能导致服务器卡顿甚至耗尽资源而崩溃！
        ///实测在4H8G机器中向3k+账号发送邮件导致服务端卡死，在32H80G中仅获取所有玩家(2k+)就耗时40秒。
        ///目前已经提交了改进建议，在优化完成之前，请谨慎使用向所有玩家发送邮件！ 的本地化字符串。
        /// </summary>
        internal static string MailSendToAllWarning {
            get {
                return ResourceManager.GetString("MailSendToAllWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 普通怪物
        ///20010101:草史莱姆
        ///20010201:大型草史莱姆
        ///20010202:大型草史莱姆-强攻强化
        ///20010301:风史莱姆
        ///20010302:风史莱姆（塔防）
        ///20010381:Slime_Wind_02 - [N/A] 1192875865
        ///20010401:大型风史莱姆
        ///20010402:大型风史莱姆（塔防）
        ///20010403:大型风史莱姆-强攻强化
        ///20010481:Slime_Wind_03 - [N/A] 401698273
        ///20010501:雷史莱姆
        ///20010502:雷史莱姆（塔防）
        ///20010503:Slime_Electric_02_SimpleStick - [N/A] 1834387465
        ///20010581:Slime_Electric_02 - [N/A] 3442560241
        ///20010601:大型雷史莱姆
        ///20010602:大型雷史莱姆（塔防）
        ///20010604:大型雷史莱姆-强攻强化
        ///20010605:Slime_Electric_03_SimpleStick - [N/A] 3051091649
        ///20010681:Sl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Monsters {
            get {
                return ResourceManager.GetString("Monsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 版本名：{0}
        ///更新时间：{1}
        ///更新内容：
        ///{2}
        ///--------------------------------------------
        ///是否查看更新？选择否将不再提醒该版本。 的本地化字符串。
        /// </summary>
        internal static string NewVersionInfo {
            get {
                return ResourceManager.GetString("NewVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. 填写正确的UID
        ///2. 向玩家发送验证码
        ///3. 输入正确的验证码
        ///4. 连接
        ///5. 享受 的本地化字符串。
        /// </summary>
        internal static string OpenCommandHelp {
            get {
                return ResourceManager.GetString("OpenCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string PageAboutTitle {
            get {
                return ResourceManager.GetString("PageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成就 的本地化字符串。
        /// </summary>
        internal static string PageAchievementTitle {
            get {
                return ResourceManager.GetString("PageAchievementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string PageAvatarTitle {
            get {
                return ResourceManager.GetString("PageAvatarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        internal static string PageCustomCommandsTitle {
            get {
                return ResourceManager.GetString("PageCustomCommandsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圣遗物 的本地化字符串。
        /// </summary>
        internal static string PageGetArtifactTitle {
            get {
                return ResourceManager.GetString("PageGetArtifactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品 的本地化字符串。
        /// </summary>
        internal static string PageGiveItemTitle {
            get {
                return ResourceManager.GetString("PageGiveItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 武器 的本地化字符串。
        /// </summary>
        internal static string PageGiveWeaponTitle {
            get {
                return ResourceManager.GetString("PageGiveWeaponTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string PageHomeTitle {
            get {
                return ResourceManager.GetString("PageHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷键 的本地化字符串。
        /// </summary>
        internal static string PageHotKey {
            get {
                return ResourceManager.GetString("PageHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件 的本地化字符串。
        /// </summary>
        internal static string PageMailTitle {
            get {
                return ResourceManager.GetString("PageMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        internal static string PageManagementTitle {
            get {
                return ResourceManager.GetString("PageManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程 的本地化字符串。
        /// </summary>
        internal static string PageOpenCommandTitle {
            get {
                return ResourceManager.GetString("PageOpenCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理 的本地化字符串。
        /// </summary>
        internal static string PageProxyTitle {
            get {
                return ResourceManager.GetString("PageProxyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务 的本地化字符串。
        /// </summary>
        internal static string PageQuestTitle {
            get {
                return ResourceManager.GetString("PageQuestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 场景项 的本地化字符串。
        /// </summary>
        internal static string PageSceneTagTitle {
            get {
                return ResourceManager.GetString("PageSceneTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 场景 的本地化字符串。
        /// </summary>
        internal static string PageSceneTitle {
            get {
                return ResourceManager.GetString("PageSceneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string PageSetPropTitle {
            get {
                return ResourceManager.GetString("PageSetPropTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string PageSettingsTitle {
            get {
                return ResourceManager.GetString("PageSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成 的本地化字符串。
        /// </summary>
        internal static string PageSpawnTitle {
            get {
                return ResourceManager.GetString("PageSpawnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环 的本地化字符串。
        /// </summary>
        internal static string PageTasksTitle {
            get {
                return ResourceManager.GetString("PageTasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天气 的本地化字符串。
        /// </summary>
        internal static string PageWeatherTitle {
            get {
                return ResourceManager.GetString("PageWeatherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要设置的权限不能为空！ 的本地化字符串。
        /// </summary>
        internal static string PermissionCannotBeEmpty {
            get {
                return ResourceManager.GetString("PermissionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *
        ///player.*
        ///player.**
        ///server.*
        ///server.**
        ///permission
        ///player.clearinv
        ///player.clearinv.others
        ///player.enterdungeon
        ///player.enterdungeon.others
        ///player.give
        ///player.give.others
        ///player.heal
        ///player.heal.others
        ///player.killcharacter
        ///player.killcharacter.others
        ///player.quest
        ///player.quest.others
        ///player.resetconstellation
        ///player.resetconstellation.others
        ///player.setfetterlevel
        ///player.setfetterlevel.others
        ///player.setprop
        ///player.setprop.others
        ///player.setstats
        ///player.setstats.others
        ///player.settalent
        ///p [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EXP:经验:
        ///BREAK_LEVEL:突破等级:
        ///SATIATION_VAL:饱食度值:
        ///SATIATION_PENALTY_TIME:饥饿惩罚时间:
        ///LEVEL:等级:[0, 90]
        ///LAST_CHANGE_AVATAR_TIME:最后更换角色的时间:
        ///MAX_SPRING_VOLUME:神像的最大回血量:
        ///CUR_SPRING_VOLUME:当前神像剩余回血量:
        ///IS_SPRING_AUTO_USE:是否靠近神像自动回血:[0, 1]
        ///SPRING_AUTO_USE_PERCENT:自动回血百分比:[0, 100]
        ///IS_FLYABLE:是否能飞:是否拥有飞行能力的状态，例如 新玩家没风之翼不能飞行[0，1]
        ///IS_WEATHER_LOCKED:是否锁定天气:
        ///IS_GAME_TIME_LOCKED:是否锁定游戏时间:
        ///IS_TRANSFERABLE:是否允许传送:
        ///MAX_STAMINA:最大耐力:玩家的最大耐力[0, 24000]
        ///CUR_PERSIST_STAMINA:当前使用的耐力:[0, 最大耐力]
        ///CUR_TEMPORARY_STAMINA:当前临时耐力:
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PlayerProperty {
            get {
                return ResourceManager.GetString("PlayerProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询服务端状态失败： 的本地化字符串。
        /// </summary>
        internal static string QueryServerStatusFailed {
            get {
                return ResourceManager.GetString("QueryServerStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30302:女神像解锁$HIDDEN - [N/A] 362713143
        ///30303:女神像解锁$HIDDEN - [N/A] 715511863
        ///30304:女神像解锁$HIDDEN - [N/A] 163018255
        ///30305:女神像解锁$HIDDEN - [N/A] 3694648119
        ///30306:女神像解锁$HIDDEN - [N/A] 3223799591
        ///30307:女神像解锁$HIDDEN - [N/A] 1232757671
        ///30308:女神像解锁$HIDDEN - [N/A] 3056513767
        ///30309:女神像解锁$HIDDEN - [N/A] 2426653367
        ///30310:女神像解锁$HIDDEN - [N/A] 2003131071
        ///30311:女神像解锁$HIDDEN - [N/A] 105277231
        ///30312:女神像解锁$HIDDEN - [N/A] 3391806215
        ///30313:女神像解锁$HIDDEN - [N/A] 1357500887
        ///30314:女神像解锁$HIDDEN - [N/A] 3054344935
        ///30315:女神像 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Quest {
            get {
                return ResourceManager.GetString("Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先连接到支持[OpenCommand]的服务器 的本地化字符串。
        /// </summary>
        internal static string RequireOpenCommandTip {
            get {
                return ResourceManager.GetString("RequireOpenCommandTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认将自定义命令恢复到默认值？ 的本地化字符串。
        /// </summary>
        internal static string RestoreCustomCommands {
            get {
                return ResourceManager.GetString("RestoreCustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1:BigWorld_LevelStreaming
        ///2:BigWorld_LevelStreaming
        ///3:提瓦特
        ///4:金苹果群岛(1.6)
        ///5:渊下宫
        ///6:层岩巨渊·地下矿区
        ///7:三界路飨祭
        ///9:金苹果群岛(2.8)
        ///10:Penumbra_LevelStreaming
        ///1001:移动平台性能测试(test)
        ///1002:攀爬测试2
        ///1003:TheBigWorld
        ///1004:Knight_Inside_Test
        ///1005:ChurchSteal
        ///1006:密林、废墟与龙之泪
        ///1008:ChurchLobby
        ///1009:AngelShare
        ///1011:角色战斗测试(test)
        ///1013:SneakAdvancedTest
        ///1015:飞翔是勇气的奖励
        ///1016:飞翔是勇气的奖励
        ///1017:壶中天
        ///1018:Chateau
        ///1019:洞天云海地城玩法测试(test)
        ///1023:Level_Yurenzhong
        ///1024:突破：清扫遗迹中的魔物(test)
        ///1030:TestIntercept_LiYue
        ///1031:爬塔丘丘人模板(test)
        ///1032:云海白 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 3
        ///101:Hdj
        ///102:JadeChamber (Default)
        ///103:JadeChamber
        ///104:Hdj
        ///105:Fhj
        ///107:KlinSeal (Default)
        ///111:Ruinup
        ///112:QLFightPlatform
        ///113:Lmboss_01 (Default)
        ///114:FlowerZone_01
        ///115:FlowerZone_02
        ///116:Lmboss_02
        ///117:LYDS_01 (Default)
        ///118:LYDS_02
        ///119:Zyj
        ///124:WinterCamp
        ///125:Hguan01 (Default)
        ///126:Hguan02
        ///127:Hguan03
        ///128:RBQyg_01
        ///129:RBQyg_02
        ///130:RBQyg_03
        ///131:RBQyg_04
        ///133:RBQyg_Stage
        ///134:TongqueTemple_Old (Default)
        ///135:TongqueTemple_New
        ///139:HZD01 (Default)
        ///140:HZD02
        ///141:CYJY_Phase1_ON (Default)        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SceneTag {
            get {
                return ResourceManager.GetString("SceneTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选中任意项！ 的本地化字符串。
        /// </summary>
        internal static string SelectAnyItem {
            get {
                return ResourceManager.GetString("SelectAnyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载设置时异常： 的本地化字符串。
        /// </summary>
        internal static string SettingLoadError {
            get {
                return ResourceManager.GetString("SettingLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置时异常： 的本地化字符串。
        /// </summary>
        internal static string SettingSaveError {
            get {
                return ResourceManager.GetString("SettingSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅允许以 Shop.json 格式保存！确定要覆盖当前指定文件吗？ 的本地化字符串。
        /// </summary>
        internal static string ShopJsonOverrideWarning {
            get {
                return ResourceManager.GetString("ShopJsonOverrideWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 900:派蒙
        ///902:礼包商城
        ///903:礼包商城
        ///1001:尘辉兑换
        ///1002:荣光之风1
        ///1003:铁匠武器店
        ///1004:蒙德杂货铺
        ///1005:猎鹿人
        ///1006:海灯
        ///1007:原萃树脂
        ///1008:东升
        ///1009:岩之印商店
        ///1010:卯师傅
        ///1011:芙萝拉
        ///1012:查尔斯
        ///1013:石榴
        ///1014:舒茨
        ///1015:布洛克
        ///1016:神奇的霍普金斯
        ///1017:杜拉夫
        ///1018:克罗丽丝
        ///1019:璃彩
        ///1020:月疏
        ///1021:阿桂
        ///1022:老高
        ///1023:老孙
        ///1024:绮命
        ///1025:张顺
        ///1026:快刀陈
        ///1027:中原杂碎店
        ///1028:石头
        ///1029:纪芳
        ///1030:朱老板
        ///1031:小白
        ///1032:老周叔？或者凯叔？
        ///1033:琳琅
        ///1034:菲尔戈黛特
        ///1035:老周叔？或者凯叔？
        ///1036:一大袋摩拉（北国银行）
        ///1037:熄星活动
        ///1038:叶卡捷琳娜（存疑）
        ///1039:哈里斯雪山前营地
        ///1040:「白垩与黑龙」活动商店兑换
        ///1041:迷你仙灵活动
        ///1042:宜年 海灯节
        ///1043:某之印商店
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ShopType {
            get {
                return ResourceManager.GetString("ShopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动代理 的本地化字符串。
        /// </summary>
        internal static string StartProxy {
            get {
                return ResourceManager.GetString("StartProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭代理 的本地化字符串。
        /// </summary>
        internal static string StopProxy {
            get {
                return ResourceManager.GetString("StopProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务已经启动，无法操作 的本地化字符串。
        /// </summary>
        internal static string TaskRunningCannotOperated {
            get {
                return ResourceManager.GetString("TaskRunningCannotOperated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token不能为空 的本地化字符串。
        /// </summary>
        internal static string TokenCannotBeEmpty {
            get {
                return ResourceManager.GetString("TokenCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已从缓存中恢复Token 的本地化字符串。
        /// </summary>
        internal static string TokenRestoredFromCache {
            get {
                return ResourceManager.GetString("TokenRestoredFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须先信任根证书才能继续！ 的本地化字符串。
        /// </summary>
        internal static string TrustedBeforeContinuing {
            get {
                return ResourceManager.GetString("TrustedBeforeContinuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空！ 的本地化字符串。
        /// </summary>
        internal static string UsernameCannotBeEmpty {
            get {
                return ResourceManager.GetString("UsernameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11101:无锋剑
        ///11201:银剑
        ///11301:冷刃
        ///11302:黎明神剑
        ///11303:旅行剑
        ///11304:暗铁剑
        ///11305:吃虎鱼刀
        ///11306:飞天御剑
        ///11401:西风剑
        ///11402:笛剑
        ///11403:祭礼剑
        ///11404:宗室长剑
        ///11405:匣里龙吟
        ///11406:试作斩岩
        ///11407:铁蜂刺
        ///11408:黑岩长剑
        ///11409:黑剑
        ///11410:暗巷闪光
        ///11412:降临之剑
        ///11413:腐殖之剑
        ///11414:天目影打刀
        ///11415:辰砂之纺锤
        ///11416:笼钓瓶一心
        ///11417:原木刀
        ///11418:西福斯的月光
        ///11419:「一心传」名刀
        ///11420:「一心传」名刀
        ///11421:「一心传」名刀
        ///11422:东花坊时雨
        ///11424:狼牙
        ///11425:海渊终曲
        ///11426:灰河渡手
        ///11427:船坞长剑
        ///11501:风鹰剑
        ///11502:天空之刃
        ///11503:苍古自由之誓
        ///11504:斫峰之刃
        ///11505:磐岩结绿
        ///11509:雾切之回光
        ///11510:波乱月白经津
        ///11511:圣显之钥
        ///11512:裁叶萃光
        ///12101: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11101:blue
        ///11201:blue
        ///11301:blue
        ///11302:blue
        ///11303:blue
        ///11304:blue
        ///11305:blue
        ///11306:blue
        ///11401:purple
        ///11402:purple
        ///11403:purple
        ///11404:purple
        ///11405:purple
        ///11406:purple
        ///11407:purple
        ///11408:purple
        ///11409:purple
        ///11410:purple
        ///11412:purple
        ///11413:purple
        ///11414:purple
        ///11415:purple
        ///11416:purple
        ///11417:purple
        ///11418:purple
        ///11419:purple
        ///11420:purple
        ///11421:purple
        ///11422:purple
        ///11424:purple
        ///11425:purple
        ///11426:purple
        ///11427:purple
        ///11501:yellow
        ///11502:yellow
        ///11503:yellow
        ///11504:yellow
        ///11505:yell [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WeaponColor {
            get {
                return ResourceManager.GetString("WeaponColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 1
        ///2139:LP_Fog_Light
        ///2140:LP_Fog_Heavy
        ///2141:LP_Fog_Light
        ///2142:LP_Fog_Light
        ///2143:LP_Fog_Light
        ///4206:Dq_HeGuan_Doom
        ///4207:Dq_HeGuan_DoomHeavy
        ///4208:Dq_HeGuan_DoomHeavyest
        ///// 3
        ///1:Md_General
        ///2:Md_WindDragon
        ///3:Md_City_Storm
        ///4:Monster_LupiBoreas
        ///1000:Md_General
        ///1001:Md_General
        ///1002:Md_General
        ///1003:Md_General
        ///1004:Md_General
        ///1005:Md_General
        ///1006:Md_City_General
        ///1007:Md_WindDragon
        ///1008:Md_City_Fenghuajie
        ///1009:Md_General
        ///1010:ActivityArena_Fire
        ///1011:ActivityArena_Sunny
        ///1012:Md_General
        ///1013: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
    }
}
